[package]
name = "lab1"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
walkdir = "2.4"
rayon = "1.8"
anyhow = "1.0"
regex = "1.12.2"
lazy_static = "1.5.0"
num_cpus = "1.17.0"
